puppetlabs/puppetlabs-pe_databases

- files/puppet_enterprise_database_backup.sh
- manifests/backup.pp
To address: https://github.com/npwalker/pe_databases/issues/3
Prior to this commit, the backup script simply backed up but never
worried about preventing the storage of too many backups.
After this commit, the backup script has a retention policy and
deletes more than the desired number of backups minus 1 backups
so that the new backup can be completed.
This will likely cause valid backups to be deleted if the backups
fail and create an empty file.  Then there will be no valid backups
if nothing is done to intervene but we're choosing that option
over running out of disk space by not aggresively deleting backups.
> Add retention policy to backup script

- CHANGELOG.md
- manifests/postgresql_settings.pp
- metadata.json
PuppetDB refactored the way facts are stored in PE 2017.2 and as
a result the fact_values table no longer exists and does not
need more aggressive autovacuuming.
Since the fact values are now inlined in the facts table, the
facts table might warrant some monitoring.
Resolves https://github.com/npwalker/pe_databases/issues/5
> Do not manage fact_values table in PuppetDB in PE 2017.2+

- CHANGELOG.md
- README.md
- files/vacuum_full_tables.sh
- manifests/backup.pp
- manifests/init.pp
- manifests/maintenance.pp
- metadata.json
We want to VACUUM FULL all the tables except reports and
resource events.  We do this across days and for some lesser used
tables we do this only once per month.
> Make cronjobs to vacuum full PuppetDB tables

- CHANGELOG.md
- files/vacuum_full_tables.sh
- metadata.json
Prior to this commit, we only did a VACUUM FULL.  However, this
already requires reading the whole table so it's advantageous to
also analyze the table at the same time.  Otherwise autovacuum
will come around and analyze the table later when it could have
already been complted during the VACUUM FULL.
After this commit, we add --analyze to vacuumdb.
> Add analyze when performing VACUUM FULL

- CHANGELOG.md
- manifests/postgresql_settings.pp
- manifests/postgresql_settings/table_settings.pp
- metadata.json
Break out table settings into its own class to avoid parameter
overload on the postgresql_settings class.
> Add autovacuum settings for certnames and catalogs

- manifests/postgresql_settings.pp
Noticed that the module had a low score on the Forge because of these style issues. This PR should help.
There's still one more issue affecting the score, and that's the unbounded dependency on puppetlabs/postgresql. I don't know enough about compatibility to put a limit on the version, so I let that one go.
> Fix puppet-lint issues to raise module's score

- .gitignore
- .pdkignore
- .rubocop.yml
- CHANGELOG.md
- Gemfile
- Rakefile
- files/puppet_enterprise_database_backup.sh
- manifests/init.pp
- metadata.json
When umask is restrictive (eg: 0077), the pe-postgres user cannot access /opt/puppetlabs/pe_databases/scripts because the mode becomes 0700 and is owned by root. This sets the mode to 0755 which allows pe-postgres to access the scripts.
I also fixed a minor logging issue in the backup script. It was putting the truncate command output to stdout instead of into the log.
This fixes https://github.com/npwalker/pe_databases/issues/19
> Set permissions on /opt/puppetlabs/pe_databases and /opt/puppetlabs/pe_databases/scripts

- README.md
Removed reference to  creating a group with name "PE Database" since this is one of the core groups now, it could be confusing to the user.
>  PE Database is a reserved node group name in 2019.0

- CHANGELOG.md
- README.md
- files/puppet_enterprise_database_backup.sh
- files/vacuum_full_tables.sh
- functions/version_based_databases.pp
- hieradata_examples/backup_schedule_alt_example_1.yaml
- hieradata_examples/backup_schedule_alt_example_2.yaml
- hieradata_examples/backup_schedule_default.yaml
- manifests/backup.pp
- manifests/init.pp
- manifests/maintenance.pp
- manifests/maintenance/pg_repack.pp
- manifests/maintenance/vacuum_full.pp
- manifests/postgresql_settings.pp
- manifests/postgresql_settings/table_settings.pp
- manifests/set_puppetdb_table_autovacuum_cost_delay_zero.pp
- manifests/set_table_attribute.pp
- metadata.json
Correct puppet lint warnings.
Correct metadata.json warnings.
Remove code supporting unsupported versions of PE.
Correct shellcheck warnings
Remove hard-coded reference to 9.4.
Normalize language and format of README.
Update for version changes.
> (refactor) correct pdk validate warnings, update for version changes

- files/puppet_enterprise_database_backup.sh
- files/vacuum_full_tables.sh
Use a more sensible timestamp for backups
Use arrays when possible
Lowercase variables
More safely process backup retention
> Refactor shell scripts

- files/puppet_enterprise_database_backup.sh
- files/vacuum_full_tables.sh
> (maint) shellcheck, spacing, and case

- manifests/maintenance/pg_repack.pp
- spec/classes/maintenance/pg_repack_spec.rb
Changes to pg_repack.pp to prevent creation of cron jobs for the resource_events table in 2019.3+ and the reports table in 2019.7+; as a result of the DELETE operation no longer running against these tables.
> Changes to pg_repack.pp per SUP-1949

- manifests/maintenance/pg_repack.pp
- spec/classes/maintenance/pg_repack_spec.rb
Prior to this commit, the repack maintenance jobs would all log to
`output.log` and clobber the log each time a job ran. This commit moves
the logs for each repack into their own file so they do not overwrite
other repack jobs logs.
> (GH-30) Update repack logging to separate files

- metadata.json
Prior to this commit, puppetlabs-cron_core was a dependency of this
module. Since cron_core is for Puppet 6+ and this module supports 5.5.x,
the cron_core module as a dependency is removed in this commit. The
cron_core module is provided in core puppet in 5.5.x and in the
puppet-agent package for 6.x, so there should not be a requirement to
install cron_core.
> (sup-2095) Remove cron_core from dependencies

- .fixtures.yml
- .rubocop.yml
- manifests/postgresql_settings.pp
- manifests/set_table_attribute.pp
- metadata.json
- spec/classes/init_spec.rb
- spec/classes/maintenance/pg_repack_spec.rb
- spec/classes/maintenance/vacuum_full_spec.rb
- spec/classes/maintenance_spec.rb
Prior to this commit, the module had dependencies for postgresql and stdlib.
stdlib appears to have been in metadata only, postgres functions are migrated to corresponding pe_postgres functions.
Passes local acceptance tests with pe_postgres module present, unsure as to how to perform spec testing utilising fixtures on internal repos in remote pipeline
> (SUP-2374) Remove external module deps

- manifests/maintenance/pg_repack.pp
- spec/classes/maintenance/pg_repack_spec.rb
Adding catalog_inputs to the pg_repack scheme for PE 2019.8.0+.
> Changes to pg_repack.pp and pg_repack_spec.rb per SUP-2405

- files/common.sh
- manifests/backup.pp
- tasks/reset_pgrepack_schema.sh
Prior to this commit shell actions where failing on Ubuntu due to the default shell and path configuration being different from EL based OS's
> Fix path in backup.pp and reset pgrepack schema task

- spec/acceptance/backup_spec.rb
- spec/acceptance/collect_spec.rb
- spec/acceptance/init_spec.rb
- spec/acceptance/tasks/reset_pgrepack_schema_spec.rb
- spec/spec_helper_acceptance_local.rb
Depends on: https://github.com/puppetlabs/puppetlabs-pe_databases/pull/74
> Add initial acceptance tests

- .github/workflows/pe_latest_testing.yml
- .github/workflows/pe_lts_testing.yml
This commit adds the streaming capabilities to the acceptance testing
bolt provisioning. This allows for better insight into the acceptance
testing output when diagnosing issues with the testing.
> (maint) Add the bolt streaming to acceptance tests

- manifests/init.pp
Prior to this commit, the default behavior was to manage various
postgresql settings such as autovacuum frequency.  However, this is not
possible during a PE upgrade because postgres is down.
> (SUP-2545) Disable table maintenance by default

- templates/timer.epp
Prior to this commit, this property created an unwanted dependency
between the timer and service. The effect is that starting the timer
will immediately start the service regardless of the schedule. Removing
this property allows the implicit relationships to work properly.
> (SUP-2682) Remove Requires= property from timers

- manifests/init.pp
- spec/acceptance/backup_spec.rb
- spec/classes/backup_spec.rb
- spec/classes/init_spec.rb
Prior to this commit, by default the pe_databases::backup class would be
included but not do anything.  That was because the logic for the class
parameter was correct
disable_maintenance => ! $manage_database_backups
But the logic to include the class was not
if defined('$manage_database_backups')
This commit fixes this logic and adds spec tests to cover it.  I also
moved the test for checking the cron resources from an acceptance test
to spec.
> (SUP-2557) Ensure backup class is not included by default

- README.md
- manifests/init.pp
- spec/acceptance/backup_spec.rb
If the parameter pe_databases::manage_database_backups is set (to true or false) a notify warning is displayed on Puppet runs about deprecation and removing this param.
This warning doesn't come up if this parameter is not set. 
Note added to readme regarding the deprecation.
> (SUP-2677) Deprecate backup functionality

- manifests/collect.pp
- manifests/init.pp
- manifests/pg_repack.pp
- manifests/postgresql_settings.pp
- manifests/postgresql_settings/table_settings.pp
- manifests/set_puppetdb_table_autovacuum_cost_delay_zero.pp
- manifests/set_table_attribute.pp
- spec/classes/pg_repack_spec.rb
Update format of comments to be picked up by puppet strings
> (SUP-3409) Update puppet strings comments

- manifests/init.pp
- manifests/pg_repack.pp
> make systemd timers configurable

- data/common.yaml
- hiera.yaml
- manifests/collect.pp
- manifests/init.pp
- manifests/pg_repack.pp
- spec/classes/pg_repack_spec.rb
- spec/defines/collect_spec.rb
This commit adds a new service and timer to repack tables in the pe-activity database.  It also moves a few parameters to module data.
> (SUP-3972) Add activity tables to repack

- data/rspec.yaml
- hiera-rspec.yaml
- manifests/pg_repack.pp
- spec/classes/pg_repack_spec.rb
Implementation of the new conditional logic to enable DEBUG and echo by default in `pg-repack.pp`, this is set by two new variables which by default are configured to:
`Enum['INFO','NOTICE','WARNING', 'ERROR', 'LOG', 'FATAL','PANIC','DEBUG'] $repack_run_level='DEBUG',
Boolean $enable_echo = true,`
For configuration of $repack_run_level, change DEBUG too one of the stored options:
`Enum['INFO','NOTICE','WARNING', 'ERROR', 'LOG', 'FATAL','PANIC','DEBUG'] $repack_run_level=<option>` and receive the relevant output in .service files
And to disable echo set `$enable_echo` to `false`
> (SUP-4666) Pe_databases: pg_repack enable debug mode
